name: flutter_gtk
description: Implementation of GTK & Adwaita widgets in Flutter.
version: 0.0.1
homepage: https://github.com/jesusrp98/expand_widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Cantarell
      fonts:
        - asset: fonts/Cantarell-Regular.otf

